### ISSUE TITLE
Add support for mora files

### ISSUE THREAD

**Issue by ToadKing** [SheamusPatt/musicbrainz-isrcsubmit#2]
The Japanese store [mora](https://mora.jp/) has ISRC tags in its files, but it does not use the `ISRC` to store them. It instead has a tag name that's a UUID, `93a74bea-ce97-5571-a56a-c5084dba9873`.

**Comment by SheamusPatt** [comment]
What file format to they use eg. Flac, MP4? The new support relies on [mutagen](https://mutagen.readthedocs.io/en/latest/user/index.html) for tagging support. As long as it's a file format they support, it wouldn't be difficult even with a unique tag name. If not, though, it would be a lot of effort.

**Comment by ToadKing** [comment]
I've only downloaded FLAC files from them so they're in FLAC/VorbisComment tags.

**Comment by SheamusPatt** [comment]
I've added that tag if it can't find ISRC, just for FLAC files. Can you try it out? You can download it [here](https://raw.githubusercontent.com/SheamusPatt/musicbrainz-isrcsubmit/SheamusPatt-mora-1/isrcDigitalSubmit.py) (save on top of the earlier isrcDigitalSubmit.py . If it works for you I'll merge it into master.

**Comment by ToadKing** [comment]
Your file doesn't run.

```
  File "/home/xxx/isrcDigitalSubmit.py", line 152
    self._isrc = track.get("ISRC") if track.get("ISRC") 
                                                        ^
SyntaxError: invalid syntax
```

**Comment by SheamusPatt** [comment]
Sorry, should have tested it first. Download it again, it should be fixed now.

**Comment by ToadKing** [comment]
Seems to work for the FLAC file I have.

```
isrcDigitalSubmit 2.2.2 by SheamusPatt
Artist:         岡部啓一
Release:        NieR Replicant -10+1 Years- (Official)
Release Event:  2021-09-15      XW
Barcode:        4988601468541
Catalog No.:    SQEX-10859-1
MusicBrainz ID: 36517959-2faf-4cf2-af6d-d00ceae7187a
JPA842003794 is already attached to track 4

No new ISRCs could be found.
```

I don't know if the AAC files they provide have tags as well. If I ever buy one of them I'll be sure to check though.

**Comment by SheamusPatt** [comment]
That's great. I'll put that into master - should show up in v2.2.2. 
Thanks for the feedback.

**Comment by SheamusPatt** [comment]
Fix committed to master, will appear in v2.2.2 release.

**Comment by ToadKing** [comment]
I bought an AAC/MP4 file from the site and it looks like they have the ISRC codes as well, but they're not in normal tags. They're in UUID atoms instead with what appears to be a somewhat custom format which is probably gonna be a huge pain to extract.

![image](https://user-images.githubusercontent.com/1023440/135766082-6ecbe485-78b0-4d5d-970f-156e8db54111.png)

**Comment by SheamusPatt** [comment]
Yes, same UUID only it's in that obscure M4A uuid tag format. the digit '0' is actually the length, I think (48 bytes). 16 bytes are the UUID (binary). 12 bytes at the end are the ISRC. I can't figure out what the bytes in the middle represent.
If you can send me the output from running mutagen_inspect.py (in the mutagen package), it might help. The script in the version I have doesn't run, though - seems to be some coding errors.
**Update**: the scripts do work quite well, only it's necessary to run "setup.py install" and run the wrappers it installs in /usr/local/bin or whatever. Just running the distributed .py versions doesn't work.

**Comment by ToadKing** [comment]
I ran the script but it doesn't print out the UUID atoms.

```
- MPEG-4 audio (AAC LC), 303.48 seconds, 319992 bps (audio/mp4)
aART=石渡 太輔, 橋本 直樹 & アークシステムワークス
covr=[1645143 bytes of data]
desc=JASRAC / NEW GUILTY GEAR(Promotion Music)
disk=(1, 0)
trkn=(1, 0)
©ART=石渡 太輔, 橋本 直樹 & アークシステムワークス
©alb=Smell of the Game (『NEW GUILTY GEAR』Promotion Music)
©cmt= 
©day= 
©gen= 
©nam=Smell of the Game (『NEW GUILTY GEAR』Promotion Music)
©prt=(P) 2019 NEW GUILTY GEAR(Promotion Music)
©wrt=石渡 太輔
```
